services:
  sales:
    image: ghcr.io/snick1914/ad-mesh-sales:latest
    container_name: ad-mesh-sales
    restart: unless-stopped
    networks:
      - ad-mesh-network
      - proxy-network

  dashboard:
    image: ghcr.io/snick1914/ad-mesh-dashboard:latest
    container_name: ad-mesh-dashboard
    restart: unless-stopped
    networks:
      - ad-mesh-network
      - proxy-network
  api:
    image: ghcr.io/snick1914/ad-mesh-api:latest
    container_name: ad-mesh-api
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - ad-mesh-network
      - proxy-network

  db:
    image: postgres:16-alpine
    container_name: ad-mesh-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: unless-stopped
    volumes:
      - ad-mesh-db-data:/var/lib/postgresql/data
    networks:
      - ad-mesh-network

networks:
  ad-mesh-network:
    driver: bridge
  proxy-network:
    external: true

volumes:
  ad-mesh-db-data:
