"""add jsonb columns for telemetry data

Revision ID: 2581d6e042f9
Revises: a5a311820fc0
Create Date: 2026-07-01 00:04:40.594263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2581d6e042f9'
down_revision = 'a5a311820fc0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('device_serial_number_key', 'device', type_='unique')
    op.drop_index('ix_device_serial_number', table_name='device')
    op.create_index(op.f('ix_device_serial_number'), 'device', ['serial_number'], unique=True)
    op.add_column('telemetry_data', sa.Column('mediciones', sa.JSON(), nullable=True))
    op.add_column('telemetry_data', sa.Column('sensores_extra', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telemetry_data', 'sensores_extra')
    op.drop_column('telemetry_data', 'mediciones')
    op.drop_index(op.f('ix_device_serial_number'), table_name='device')
    op.create_index('ix_device_serial_number', 'device', ['serial_number'], unique=False)
    op.create_unique_constraint('device_serial_number_key', 'device', ['serial_number'])
    # ### end Alembic commands ###
