"""add linking_code to user

Revision ID: 354a7018e147
Revises: 90056650be1b
Create Date: 2026-07-20 23:21:53.239561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '354a7018e147'
down_revision = '90056650be1b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('linking_code', sa.String(), nullable=True))
    op.create_index(op.f('ix_user_linking_code'), 'user', ['linking_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_linking_code'), table_name='user')
    op.drop_column('user', 'linking_code')
    # ### end Alembic commands ###
