"""add_soft_delete_to_media

Revision ID: 8e3940d361cd
Revises: a3b4c5d6e7f8
Create Date: 2026-05-17 03:11:50.030017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e3940d361cd'
down_revision = 'a3b4c5d6e7f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('media', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_media_is_deleted'), 'media', ['is_deleted'], unique=False)
    op.add_column('user', sa.Column('company_name', sa.String(), nullable=True))
    op.add_column('user', sa.Column('max_devices', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('max_storage_gb', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_company_name'), 'user', ['company_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_company_name'), table_name='user')
    op.drop_column('user', 'max_storage_gb')
    op.drop_column('user', 'max_devices')
    op.drop_column('user', 'company_name')
    op.drop_index(op.f('ix_media_is_deleted'), table_name='media')
    op.drop_column('media', 'deleted_at')
    op.drop_column('media', 'is_deleted')
    # ### end Alembic commands ###
