"""add baud_rate to device

Revision ID: 90056650be1b
Revises: 2581d6e042f9
Create Date: 2026-07-17 02:58:13.826600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90056650be1b'
down_revision = '2581d6e042f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('baud_rate', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'baud_rate')
    # ### end Alembic commands ###
