"""create_telemetry_table

Revision ID: a5a311820fc0
Revises: c2d3e4f5a6b7
Create Date: 2026-06-30 05:46:22.744014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5a311820fc0'
down_revision = 'c2d3e4f5a6b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('device_serial_number_key', 'device', type_='unique')
    op.drop_index('ix_device_serial_number', table_name='device')
    op.create_index(op.f('ix_device_serial_number'), 'device', ['serial_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_serial_number'), table_name='device')
    op.create_index('ix_device_serial_number', 'device', ['serial_number'], unique=False)
    op.create_unique_constraint('device_serial_number_key', 'device', ['serial_number'])
    # ### end Alembic commands ###
